### PR TITLE
userHasExplicitlySetTheTheme and UI flicker fix

### LINKED ISSUE #32: userHasExplicitlySetTheTheme and UI flicker
Not sure if it's just user error from me, but when I set `current: 'light'`, I still see a flicker of dark mode (if my system preference is that) before the page properly initialises. The only way I could get this to stop, was in the config inside `preview.ts` I forced the hidden `userHasExplicitlySetTheTheme` property to true. This made the addon avoid applying a `dark` class before switching to `light`.

I think there might be a timing issue in the addon that is respecting system-preference before Storybook config, but I could very easily be mistaken!

Anyway just wanted to flag as this took me a little while to figure out 😂 

Thank you!

My config code in `preview.ts`

```
darkMode: {
  current: 'light',
  // This forces the addon to initially render in light mode. If we dont do this, there is an initial flicker of the system-preference theme that only stops when the user explicitly clicks light/dark in the Storybook UI.
  userHasExplicitlySetTheTheme: true,
  // Override the default dark theme
  dark: { ...getTheme('dark') },
  light: { ...getTheme() },
},
```

### PR DESCRIPTION
**Pull request by KinduD21**
Improved theme management and updated dark mode logic:
- Changed initial state for dark mode to use the current store value.
- Introduced refs to manage theme parameters and deferred updates.
- Enhanced the prefersDarkUpdate function with useCallback for better performance.
- Updated theme rendering logic to handle changes in storybook parameters more effectively.
- Simplified theme initialization in the manager by using nullish coalescing.

### CODE REVIEW

File: src/Tool.tsx [hunk 1]
```diff
@@ -21,10 +21,14 @@ interface DarkModeProps {
 
 /** A toolbar icon to toggle between dark and light themes in storybook */
 export function DarkMode({ api }: DarkModeProps) {
-  const [isDark, setDark] = React.useState(prefersDark.matches);
+  const [isDark, setDark] = React.useState(() => store().current === "dark");
```
Comment (itsJohnnyGrid) [inline src/Tool.tsx]: store().current better move to const

**Review by itsJohnnyGrid — APPROVED** [review]
